    <link rel="stylesheet" href="components/css/nav.css">
    <link rel="stylesheet" href="components/css/FooterCSS.css">
    <link rel="stylesheet" href="components/css/contentAboutUs.css">
    <link rel="stylesheet" href="components/css/contentMerken.css">
    <link rel="stylesheet" href="components/css/index.css">
    <link rel="stylesheet" href="components/css/contentMain.css">
    <link rel="stylesheet" href="components/css/contentSpaar.css">
    <link rel="stylesheet" href="components/css/contentActies.css">
    <link rel="stylesheet" href="components/css/contentLijst.css">
